import type { GameCmsContent } from './gameCmsSchema';
import type { GameUiPlacements } from './gamePlacementSchema';
import type { GameUiTheme } from './gameUiThemeSchema';

const condensed = '"IBM Plex Sans Condensed", "Arial Narrow", ui-sans-serif, system-ui, sans-serif';
const din = '"DIN Condensed", "Bahnschrift", "Arial Narrow", ui-sans-serif, system-ui, sans-serif';
const mono = '"JetBrains Mono", ui-monospace, monospace';

const darkSurfaces: GameUiTheme['surfaces'] = {
  topBar: {
    surface: {
      material: 'custom',
      materialColor: '#23241f',
      texture: 'road012a',
      textureStrength: 54,
      gradient: 'both',
      lightStrength: 18,
      darkStrength: 42,
      borderEnabled: true,
      borderColor: 'inherit',
      borderOpacity: 34,
      radius: 12,
      glass: true,
      glassOpacity: 24,
      glassBlurEnabled: true,
      glassBlur: 8,
    },
  },
  resourceChip: {
    surface: {
      material: 'custom',
      materialColor: '#191d20',
      glass: true,
      glassOpacity: 32,
      borderEnabled: true,
      borderOpacity: 38,
      radius: 8,
      contentTone: 'white',
      textEmboss: true,
    },
  },
  bottomNavContainer: {
    surface: {
      material: 'custom',
      materialColor: '#161a1b',
      glass: true,
      glassOpacity: 36,
      texture: 'road012a',
      textureStrength: 42,
      borderEnabled: true,
      borderOpacity: 32,
      radius: 12,
    },
  },
  bottomNavItem: {
    surface: {
      material: 'custom',
      materialColor: '#242621',
      texture: 'road012a',
      textureStrength: 58,
      borderEnabled: true,
      borderOpacity: 28,
      radius: 8,
      contentTone: 'white',
      textEmboss: true,
    },
    states: {
      hover: { surfaceLayerBrightness: 1.1 },
      pressed: { surfaceLayerBrightness: 1.1, stateTranslateY: 1 },
    },
  },
  bottomNavActiveItem: {
    surface: {
      material: 'custom',
      materialColor: '#56421e',
      texture: 'road012a',
      textureStrength: 64,
      borderEnabled: true,
      borderColor: 'custom',
      borderCustomColor: '#d6a94a',
      borderOpacity: 62,
      glow: 'gold',
      glowStrength: 34,
      radius: 8,
      contentTone: 'gold',
      textEmboss: true,
    },
  },
  heroPromo: {
    surface: {
      material: 'custom',
      materialColor: '#111820',
      glass: true,
      glassOpacity: 28,
      borderEnabled: true,
      borderCustomColor: '#d6a94a',
      borderColor: 'custom',
      borderOpacity: 52,
      radius: 14,
      contentTone: 'white',
    },
  },
  promoCard: {
    surface: {
      material: 'white',
      texture: 'road012a',
      textureStrength: 48,
      gradient: 'both',
      lightStrength: 18,
      darkStrength: 28,
      borderEnabled: true,
      borderOpacity: 26,
      radius: 10,
      contentTone: 'black',
    },
  },
  ctaPrimary: {
    surface: {
      material: 'custom',
      materialColor: '#c7a04d',
      gradient: 'both',
      lightStrength: 30,
      darkStrength: 18,
      borderEnabled: true,
      borderOpacity: 36,
      radius: 7,
      contentTone: 'black',
      textEmboss: true,
    },
    states: {
      hover: { surfaceLayerBrightness: 1.16 },
      pressed: { surfaceLayerBrightness: 1.16, stateTranslateY: 2 },
    },
  },
  ctaSecondary: {
    surface: {
      material: 'custom',
      materialColor: '#252722',
      texture: 'road012a',
      textureStrength: 52,
      borderEnabled: true,
      borderOpacity: 28,
      radius: 7,
      contentTone: 'white',
      textEmboss: true,
    },
  },
};

const lightSurfaces: GameUiTheme['surfaces'] = {
  ...darkSurfaces,
  topBar: {
    surface: {
      material: 'white',
      materialColor: '#f3eee4',
      texture: 'concrete002',
      textureStrength: 18,
      gradient: 'top-light',
      lightStrength: 20,
      borderEnabled: true,
      borderOpacity: 24,
      radius: 14,
      contentTone: 'black',
    },
  },
  resourceChip: {
    surface: {
      material: 'white',
      materialColor: '#f6f2eb',
      borderEnabled: true,
      borderOpacity: 18,
      radius: 8,
      contentTone: 'black',
      textEmboss: false,
    },
  },
  bottomNavContainer: {
    surface: {
      material: 'white',
      materialColor: '#f2ede4',
      borderEnabled: true,
      borderOpacity: 20,
      radius: 12,
      contentTone: 'black',
    },
  },
  bottomNavItem: {
    surface: {
      material: 'white',
      materialColor: '#f4efe6',
      borderEnabled: true,
      borderOpacity: 18,
      radius: 8,
      contentTone: 'black',
    },
  },
  bottomNavActiveItem: {
    surface: {
      material: 'custom',
      materialColor: '#211f1a',
      borderEnabled: true,
      borderColor: 'custom',
      borderCustomColor: '#c79b43',
      borderOpacity: 64,
      glow: 'gold',
      glowStrength: 24,
      radius: 8,
      contentTone: 'gold',
      textEmboss: true,
    },
  },
  heroPromo: {
    surface: {
      material: 'white',
      materialColor: '#f5f0e8',
      borderEnabled: true,
      borderCustomColor: '#d3b16c',
      borderColor: 'custom',
      borderOpacity: 42,
      radius: 14,
      contentTone: 'black',
    },
  },
};

const baseTextStyles: GameUiTheme['textStyles'] = {
  shellLabel: { tone: 'textMuted', font: 'condensed', sizeRem: 0.72, weight: 700, letterSpacing: 0.08, transform: 'uppercase' },
  profileName: { tone: 'textPrimary', font: 'condensed', sizeRem: 0.95, weight: 700, letterSpacing: 0.04, transform: 'uppercase' },
  resourceAmount: { tone: 'textPrimary', font: 'numeric', sizeRem: 0.95, weight: 700, letterSpacing: 0.03 },
  resourceLabel: { tone: 'textMuted', font: 'condensed', sizeRem: 0.58, weight: 600, letterSpacing: 0.08, transform: 'uppercase' },
  navLabel: { tone: 'textPrimary', font: 'condensed', sizeRem: 0.68, weight: 600, letterSpacing: 0.08, transform: 'uppercase' },
  navLabelActive: { tone: 'gold', font: 'condensed', sizeRem: 0.68, weight: 700, letterSpacing: 0.08, transform: 'uppercase', embossMode: 'shadow', embossStrength: 32 },
  promoEyebrow: { tone: 'gold', font: 'condensed', sizeRem: 0.68, weight: 700, letterSpacing: 0.1, transform: 'uppercase' },
  promoTitle: { tone: 'textPrimary', font: 'heading', sizeRem: 1.35, weight: 800, letterSpacing: 0.04, transform: 'uppercase' },
  promoBody: { tone: 'textMuted', font: 'body', sizeRem: 0.78, weight: 400, lineHeight: 1.35 },
  ctaLabel: { tone: 'textInverse', font: 'condensed', sizeRem: 0.78, weight: 800, letterSpacing: 0.06, transform: 'uppercase', embossMode: 'shadow', embossStrength: 28 },
};

export const darkStoneGameUiThemeFixture: GameUiTheme = {
  schemaVersion: 1,
  id: 'dark-stone',
  label: 'Dark Stone',
  palette: {
    bg: '#090d10',
    panelStone: '#343029',
    panelDark: '#15191c',
    panelLight: '#d7cdb8',
    textPrimary: '#f3eee3',
    textMuted: '#a9a398',
    textInverse: '#19150e',
    gold: '#d9ad4f',
    cyan: '#33b9f2',
    danger: '#ff655a',
    success: '#5bd38c',
    divider: '#6d6659',
  },
  typography: {
    heading: { family: din, weight: 800, letterSpacing: 0.04, lineHeight: 1 },
    body: { family: condensed, weight: 400, letterSpacing: 0.02, lineHeight: 1.35 },
    condensed: { family: condensed, weight: 700, letterSpacing: 0.06, lineHeight: 1.1 },
    mono: { family: mono, weight: 600, letterSpacing: 0.02, lineHeight: 1.2 },
    numeric: { family: din, weight: 700, letterSpacing: 0.03, lineHeight: 1 },
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 18, xl: 28, density: 'compact' },
  radius: { sm: 5, md: 8, lg: 14, pill: 24 },
  icon: { sm: 16, md: 24, lg: 36, strokeWidth: 2 },
  surfaces: darkSurfaces,
  textStyles: baseTextStyles,
  skins: {
    screenShell: { backgroundTone: 'bg', backgroundImageId: 'new-eden-dusk', backgroundDim: 28, safeAreaPadding: 'md', contentDensity: 'compact' },
    topBar: { surface: 'topBar', profileText: 'profileName', resourceAmountText: 'resourceAmount', resourceLabelText: 'resourceLabel', gap: 'md', avatarSize: 'md', resourceChipVariant: 'glass' },
    resourceChip: { surface: 'resourceChip', amountText: 'resourceAmount', labelText: 'resourceLabel', iconTone: 'gold', showLabel: true, showPlusButton: true },
    bottomNav: { containerSurface: 'bottomNavContainer', itemSurface: 'bottomNavItem', activeItemSurface: 'bottomNavActiveItem', labelText: 'navLabel', activeLabelText: 'navLabelActive', iconSize: 'md', activeIndicator: 'glow' },
    toolbar: { containerSurface: 'topBar', itemSurface: 'bottomNavItem', activeItemSurface: 'bottomNavActiveItem', labelText: 'navLabel', showLabels: true },
    promoCard: { surface: 'promoCard', titleText: 'promoTitle', bodyText: 'promoBody', eyebrowText: 'promoEyebrow', ctaSkin: 'secondary', mediaTreatment: 'right-cutout', emphasis: 'standard' },
    heroPromo: { surface: 'heroPromo', titleText: 'promoTitle', bodyText: 'promoBody', eyebrowText: 'promoEyebrow', ctaSkin: 'primary', mediaTreatment: 'background', emphasis: 'featured', minHeight: 'lg', overlay: 'left-gradient' },
    cta: {
      primary: { surface: 'ctaPrimary', labelText: 'ctaLabel', iconTone: 'gold', iconPosition: 'right', minHeight: 44 },
      secondary: { surface: 'ctaSecondary', labelText: 'ctaLabel', iconTone: 'gold', iconPosition: 'right', minHeight: 38 },
    },
  },
};

export const lightMarbleGameUiThemeFixture: GameUiTheme = {
  ...darkStoneGameUiThemeFixture,
  id: 'light-marble',
  label: 'Light Marble',
  palette: {
    bg: '#f6f2eb',
    panelStone: '#eee8dd',
    panelDark: '#24211c',
    panelLight: '#fbf8f2',
    textPrimary: '#15130f',
    textMuted: '#746d62',
    textInverse: '#ffffff',
    gold: '#b98b31',
    cyan: '#2c9ed0',
    danger: '#b94b45',
    success: '#3a9f67',
    divider: '#cfc6b8',
  },
  spacing: { xs: 5, sm: 10, md: 16, lg: 24, xl: 36, density: 'comfortable' },
  surfaces: lightSurfaces,
  textStyles: {
    ...baseTextStyles,
    ctaLabel: { ...baseTextStyles.ctaLabel, tone: 'textInverse' },
  },
  skins: {
    ...darkStoneGameUiThemeFixture.skins,
    screenShell: { backgroundTone: 'bg', backgroundImageId: 'kitsune-white-city', backgroundDim: 8, safeAreaPadding: 'lg', contentDensity: 'comfortable' },
    resourceChip: { ...darkStoneGameUiThemeFixture.skins.resourceChip, iconTone: 'cyan' },
  },
};

export const gameCmsFixture: GameCmsContent = {
  schemaVersion: 1,
  locale: 'en-US',
  profile: {
    id: 'netrunner-07',
    displayName: 'Netrunner_07',
    title: 'Commander',
    level: 24,
    xpCurrent: 18450,
    xpMax: 24000,
    avatarImageId: 'avatar-netrunner-07',
    badgeImageId: 'badge-sector-07',
  },
  resources: {
    credits: { id: 'credits', label: 'Credits', amount: 2450, iconId: 'resource-credits', tone: 'gold', action: { id: 'openCurrencyStore', params: { resourceId: 'credits' } } },
    data: { id: 'data', label: 'Data', amount: 870, iconId: 'resource-data', tone: 'cyan', action: { id: 'openCurrencyStore', params: { resourceId: 'data' } } },
    shards: { id: 'shards', label: 'Shards', amount: 120, iconId: 'resource-shards', tone: 'danger', action: { id: 'openCurrencyStore', params: { resourceId: 'shards' } } },
  },
  nav: {
    bottom: [
      { id: 'collection', label: 'Collection', iconId: 'nav-collection', routeId: 'collection' },
      { id: 'operations', label: 'Operations', iconId: 'nav-operations', routeId: 'operations', badge: 'dot' },
      { id: 'home', label: 'Home', iconId: 'nav-home', routeId: 'home' },
      { id: 'market', label: 'Market', iconId: 'nav-market', routeId: 'market' },
      { id: 'profile', label: 'Profile', iconId: 'nav-profile', routeId: 'profile' },
    ],
    toolbar: [
      { id: 'messages', label: 'Messages', iconId: 'toolbar-messages', routeId: 'messages', badge: 'dot' },
      { id: 'news', label: 'News', iconId: 'toolbar-news', routeId: 'news' },
      { id: 'missions', label: 'Missions', iconId: 'toolbar-missions', routeId: 'missions' },
      { id: 'events', label: 'Events', iconId: 'toolbar-events', routeId: 'events' },
    ],
  },
  promos: {
    'season-cosmic-eclipse': {
      id: 'season-cosmic-eclipse',
      kind: 'season',
      eyebrow: 'Season Pass',
      title: 'Cosmic Eclipse',
      body: 'A new era of power. Claim the darkness.',
      imageId: 'promo-cosmic-eclipse',
      focalPoint: { x: 0.64, y: 0.42 },
      cta: { label: 'View Season', action: { id: 'openEvent', params: { eventId: 'cosmic-eclipse' } } },
      startsAt: '2026-06-01T00:00:00Z',
      endsAt: '2026-06-30T00:00:00Z',
      priority: 100,
      analyticsId: 'home_hero_cosmic_eclipse',
    },
    'store-weekend-crate': {
      id: 'store-weekend-crate',
      kind: 'store',
      eyebrow: 'Limited Offer',
      title: 'Weekend Crate',
      body: 'Secure rare gear and bonus data before reset.',
      imageId: 'promo-weekend-crate',
      focalPoint: { x: 0.5, y: 0.5 },
      cta: { label: 'Open Store', action: { id: 'openStoreOffer', params: { offerId: 'weekend-crate' } } },
      startsAt: '2026-06-05T00:00:00Z',
      endsAt: '2026-06-08T00:00:00Z',
      priority: 80,
      analyticsId: 'home_hero_weekend_crate',
    },
    'community-bulletin': {
      id: 'community-bulletin',
      kind: 'community',
      eyebrow: 'Community',
      title: 'Kitsune Bulletin',
      body: 'Developer updates and community news.',
      cta: { label: 'Read More', action: { id: 'openNews', params: { newsId: 'community-bulletin' } } },
      priority: 20,
    },
  },
  news: {
    'patch-1-4': {
      id: 'patch-1-4',
      category: 'patch',
      title: 'Update 1.4.0',
      summary: 'Navigation rework, faster load times, and spatial UI fixes.',
      cta: { label: 'View Details', action: { id: 'openNews', params: { newsId: 'patch-1-4' } } },
      publishedAt: '2026-06-04T18:00:00Z',
    },
    'void-front': {
      id: 'void-front',
      category: 'event',
      title: 'Void Front Initiative',
      summary: 'Limited-time event ends in 6D 12H.',
      cta: { label: 'Enter Event', action: { id: 'openEvent', params: { eventId: 'void-front' } } },
      publishedAt: '2026-06-05T16:00:00Z',
    },
  },
  storeOffers: {
    'weekend-crate': {
      id: 'weekend-crate',
      title: 'Weekend Crate',
      description: 'Rare gear, credits, and limited contract tools.',
      priceResourceId: 'credits',
      priceAmount: 5400,
      rewardIds: ['reward-data-coil', 'reward-credits'],
      imageId: 'store-weekend-crate',
      cta: { label: 'Inspect Offer', action: { id: 'openStoreOffer', params: { offerId: 'weekend-crate' } } },
      startsAt: '2026-06-05T00:00:00Z',
      endsAt: '2026-06-08T00:00:00Z',
    },
  },
  missions: {
    'data-extraction': {
      id: 'data-extraction',
      title: 'Data Extraction',
      faction: 'Solace Corp',
      location: 'Central Node',
      description: 'Extract encrypted corporate data from Solace Corp mainframe cluster.',
      rewardResourceId: 'credits',
      rewardAmount: 1850,
      difficulty: 'hard',
      estimatedMinutes: 45,
      cta: { label: 'View Contract', action: { id: 'openMission', params: { missionId: 'data-extraction' } } },
    },
  },
  decks: {
    assault: {
      id: 'assault',
      title: 'Assault',
      archetype: 'Aggressive. Relentless. Overwhelming.',
      power: 12480,
      rank: 'Diamond I',
      cardCount: 42,
      maxCards: 42,
      imageId: 'deck-assault-mech',
      cta: { label: 'Edit Loadout', action: { id: 'openDeck', params: { deckId: 'assault' } } },
    },
  },
};

export const homePlacementFixtureA: GameUiPlacements = {
  schemaVersion: 1,
  home: {
    heroPromo: 'season-cosmic-eclipse',
    newsRail: ['patch-1-4', 'void-front', 'community-bulletin'],
    storePromo: 'store-weekend-crate',
    activeMission: 'data-extraction',
    deckSummary: 'assault',
  },
  shell: {
    bottomNav: ['collection', 'operations', 'home', 'market', 'profile'],
    toolbar: ['messages', 'news', 'missions', 'events'],
    topBarResources: ['credits', 'data'],
  },
  store: {
    featuredOffer: 'weekend-crate',
    offerRail: ['weekend-crate'],
  },
};

export const homePlacementFixtureB: GameUiPlacements = {
  ...homePlacementFixtureA,
  home: {
    ...homePlacementFixtureA.home,
    heroPromo: 'store-weekend-crate',
    newsRail: ['void-front', 'patch-1-4'],
  },
  shell: {
    ...homePlacementFixtureA.shell,
    topBarResources: ['credits', 'data', 'shards'],
  },
};
