// AUTO-GENERATED by npm run locations:generate. Do not edit by hand.
import type { AuthoredLocationDef, LocationSetMetadata } from '../../location-set-loader';
import CoreV1LocationSet from './set.json';

import AmmoClubLocation from './locations/ammo-club/location.json';
import BackdoorLocation from './locations/backdoor/location.json';
import BlackClinicLocation from './locations/black-clinic/location.json';
import BlackHaloLocation from './locations/black-halo/location.json';
import ChargingStationLocation from './locations/charging-station/location.json';
import ChipTuneLocation from './locations/chip-tune/location.json';
import ChromeBeachLocation from './locations/chrome-beach/location.json';
import ChromeDepotLocation from './locations/chrome-depot/location.json';
import CivilCourtLocation from './locations/civil-court/location.json';
import CourthouseLocation from './locations/courthouse/location.json';
import CryoStorageLocation from './locations/cryo-storage/location.json';
import CryobankLocation from './locations/cryobank/location.json';
import DarkAlleyLocation from './locations/dark-alley/location.json';
import DataChapelLocation from './locations/data-chapel/location.json';
import DebtAlleyLocation from './locations/debt-alley/location.json';
import DroneHiveLocation from './locations/drone-hive/location.json';
import FederalCourthouseLocation from './locations/federal-courthouse/location.json';
import GunStoreLocation from './locations/gun-store/location.json';
import HelixdyneLabLocation from './locations/helixdyne-lab/location.json';
import KurotekAtriumLocation from './locations/kurotek-atrium/location.json';
import MeridianTowerLocation from './locations/meridian-tower/location.json';
import NeonReliquaryLocation from './locations/neon-reliquary/location.json';
import NetrunnerShrineLocation from './locations/netrunner-shrine/location.json';
import OrganBankLocation from './locations/organ-bank/location.json';
import OverclockRoomLocation from './locations/overclock-room/location.json';
import PawnShopLocation from './locations/pawn-shop/location.json';
import PowerSinkLocation from './locations/power-sink/location.json';
import PublicPoolLocation from './locations/public-pool/location.json';
import RedNeedleLocation from './locations/red-needle/location.json';
import RentAWreckLocation from './locations/rent-a-wreck/location.json';
import RuinLocation from './locations/ruin/location.json';
import ScrapYardLocation from './locations/scrap-yard/location.json';
import SignalPitLocation from './locations/signal-pit/location.json';
import SkyrailLocation from './locations/skyrail/location.json';
import SuperchargingStationLocation from './locations/supercharging-station/location.json';
import TheCageLocation from './locations/the-cage/location.json';
import TheMeatMarketLocation from './locations/the-meat-market/location.json';
import ThePineappleClubLocation from './locations/the-pineapple-club/location.json';

export const CORE_V1_LOCATION_SET = CoreV1LocationSet as unknown as LocationSetMetadata;

export const CORE_V1_LOCATION_MODULES: readonly { folder: string; location: AuthoredLocationDef }[] = [
  { folder: 'ammo-club', location: AmmoClubLocation as unknown as AuthoredLocationDef },
  { folder: 'backdoor', location: BackdoorLocation as unknown as AuthoredLocationDef },
  { folder: 'black-clinic', location: BlackClinicLocation as unknown as AuthoredLocationDef },
  { folder: 'black-halo', location: BlackHaloLocation as unknown as AuthoredLocationDef },
  { folder: 'charging-station', location: ChargingStationLocation as unknown as AuthoredLocationDef },
  { folder: 'chip-tune', location: ChipTuneLocation as unknown as AuthoredLocationDef },
  { folder: 'chrome-beach', location: ChromeBeachLocation as unknown as AuthoredLocationDef },
  { folder: 'chrome-depot', location: ChromeDepotLocation as unknown as AuthoredLocationDef },
  { folder: 'civil-court', location: CivilCourtLocation as unknown as AuthoredLocationDef },
  { folder: 'courthouse', location: CourthouseLocation as unknown as AuthoredLocationDef },
  { folder: 'cryo-storage', location: CryoStorageLocation as unknown as AuthoredLocationDef },
  { folder: 'cryobank', location: CryobankLocation as unknown as AuthoredLocationDef },
  { folder: 'dark-alley', location: DarkAlleyLocation as unknown as AuthoredLocationDef },
  { folder: 'data-chapel', location: DataChapelLocation as unknown as AuthoredLocationDef },
  { folder: 'debt-alley', location: DebtAlleyLocation as unknown as AuthoredLocationDef },
  { folder: 'drone-hive', location: DroneHiveLocation as unknown as AuthoredLocationDef },
  { folder: 'federal-courthouse', location: FederalCourthouseLocation as unknown as AuthoredLocationDef },
  { folder: 'gun-store', location: GunStoreLocation as unknown as AuthoredLocationDef },
  { folder: 'helixdyne-lab', location: HelixdyneLabLocation as unknown as AuthoredLocationDef },
  { folder: 'kurotek-atrium', location: KurotekAtriumLocation as unknown as AuthoredLocationDef },
  { folder: 'meridian-tower', location: MeridianTowerLocation as unknown as AuthoredLocationDef },
  { folder: 'neon-reliquary', location: NeonReliquaryLocation as unknown as AuthoredLocationDef },
  { folder: 'netrunner-shrine', location: NetrunnerShrineLocation as unknown as AuthoredLocationDef },
  { folder: 'organ-bank', location: OrganBankLocation as unknown as AuthoredLocationDef },
  { folder: 'overclock-room', location: OverclockRoomLocation as unknown as AuthoredLocationDef },
  { folder: 'pawn-shop', location: PawnShopLocation as unknown as AuthoredLocationDef },
  { folder: 'power-sink', location: PowerSinkLocation as unknown as AuthoredLocationDef },
  { folder: 'public-pool', location: PublicPoolLocation as unknown as AuthoredLocationDef },
  { folder: 'red-needle', location: RedNeedleLocation as unknown as AuthoredLocationDef },
  { folder: 'rent-a-wreck', location: RentAWreckLocation as unknown as AuthoredLocationDef },
  { folder: 'ruin', location: RuinLocation as unknown as AuthoredLocationDef },
  { folder: 'scrap-yard', location: ScrapYardLocation as unknown as AuthoredLocationDef },
  { folder: 'signal-pit', location: SignalPitLocation as unknown as AuthoredLocationDef },
  { folder: 'skyrail', location: SkyrailLocation as unknown as AuthoredLocationDef },
  { folder: 'supercharging-station', location: SuperchargingStationLocation as unknown as AuthoredLocationDef },
  { folder: 'the-cage', location: TheCageLocation as unknown as AuthoredLocationDef },
  { folder: 'the-meat-market', location: TheMeatMarketLocation as unknown as AuthoredLocationDef },
  { folder: 'the-pineapple-club', location: ThePineappleClubLocation as unknown as AuthoredLocationDef },
];
