import { createMaterialRecipe, createMaterialStateOverlays } from './MaterialRecipeTypes';

export const navTabMaterialRecipe = createMaterialRecipe({
  material: 'raw',
  texture: 'stone04',
  textureStrength: 48,
  textureScale: 256,
  glass: true,
  glassOpacity: 24,
  glassBlur: 8,
  tint: 'white',
  tintStrength: 10,
  gradient: 'top-light',
  borderOpacity: 34,
  lightStrength: 48,
  darkStrength: 28,
  radius: 6,
  contentTone: 'muted',
  iconTone: 'inherit',
  textSizeRem: 0.5,
  fontWeight: 700,
  fontStyle: 'italic',
  textTransform: 'uppercase',
  letterSpacing: 0,
  states: createMaterialStateOverlays({
    hover: {
      enabled: true,
      surface: {
        tint: 'gold',
        tintStrength: 8,
        borderOpacityBoost: 10,
        lightStrengthBoost: 8,
      },
      glow: {
        tone: 'gold',
        glowStrength: 24,
        corners: ['top-left', 'top-right'],
        edgeHighlight: ['top'],
        cornerSize: 14,
      },
      content: {
        contentTone: 'gold',
        iconTone: 'inherit',
        contentGlowStrength: 12,
        iconGlowStrength: 18,
      },
    },
    active: {
      enabled: true,
      surface: {
        tint: 'gold',
        tintStrength: 34,
        borderOpacityBoost: 24,
        lightStrengthBoost: 18,
        darkStrengthBoost: 8,
      },
      glow: {
        tone: 'gold',
        glowStrength: 56,
        corners: ['top-left', 'top-right', 'bottom-right', 'bottom-left'],
        edgeHighlight: ['top', 'bottom'],
        cornerSize: 18,
      },
      emission: {
        emission: 'rail-and-blip',
        emissionEdge: 'bottom',
        emissionTone: 'gold',
        emissionStrength: 70,
        emissionLength: 54,
        emissionThickness: 2,
        emissionBlipSize: 18,
      },
      content: {
        contentTone: 'black',
        iconTone: 'black',
        fontWeight: 700,
        fontStyle: 'italic',
        textTransform: 'uppercase',
        letterSpacing: 0,
      },
    },
    pressed: {
      enabled: true,
      surface: {
        tint: 'gold',
        tintStrength: 44,
        borderOpacityBoost: 28,
        lightStrengthBoost: 12,
        darkStrengthBoost: 16,
      },
      glow: {
        tone: 'gold',
        glowStrength: 68,
        corners: ['bottom-left', 'bottom-right'],
        edgeHighlight: ['bottom'],
        cornerSize: 18,
      },
      emission: {
        emission: 'center-blip',
        emissionEdge: 'bottom',
        emissionTone: 'gold',
        emissionStrength: 80,
        emissionLength: 36,
        emissionThickness: 3,
        emissionBlipSize: 20,
      },
      content: {
        contentTone: 'black',
        iconTone: 'inherit',
        fontWeight: 700,
        fontStyle: 'italic',
        textTransform: 'uppercase',
        letterSpacing: 0,
      },
      motion: {
        translateY: 1,
        scale: 0.985,
      },
    },
  }),
});
