import { createMaterialRecipe, createMaterialStateOverlays } from './MaterialRecipeTypes';

export const navTabMaterialRecipe = createMaterialRecipe({
  material: 'custom',
  materialColor: '#707275',
  texture: 'stone04',
  textureStrength: 84,
  textureScale: 256,
  glass: true,
  glassOpacity: 15,
  glassBlur: 3,
  tint: 'none',
  tintStrength: 0,
  gradient: 'both',
  borderEnabled: true,
  border: ['top', 'right', 'bottom', 'left'],
  borderColor: 'custom',
  borderCustomColor: '#eaeaea',
  borderOpacity: 54,
  lightStrength: 62,
  darkStrength: 36,
  sheen: true,
  edgeWearTexture: 'edge-bw-noise-dense',
  edgeWearOpacity: 45,
  edgeWearWidth: 1,
  edgeWearScale: 1024,
  edgeWearLayer: 'above-highlights',
  dropShadow: true,
  shadowOpacity: 58,
  shadowBlur: 6,
  shadowX: 0,
  shadowY: 3,
  shadowSpread: 0,
  radius: 6,
  contentTone: 'black',
  iconTone: 'inherit',
  textSizeRem: 0.72,
  fontWeight: 800,
  fontStyle: 'normal',
  textTransform: 'uppercase',
  letterSpacing: 0.05,
  states: createMaterialStateOverlays({
    hover: {
      enabled: true,
      surface: {
        tint: 'gold',
        tintStrength: 8,
        borderOpacityBoost: 8,
        lightStrengthBoost: 8,
      },
      glow: {
        tone: 'gold',
        glowStrength: 1,
        corners: ['top-left', 'top-right', 'bottom-right', 'bottom-left'],
        edgeHighlight: ['top'],
        cornerSize: 17,
      },
      content: {
        contentTone: 'inherit',
        iconTone: 'inherit',
        contentGlowStrength: 0,
        iconGlowStrength: 20,
      },
    },
    active: {
      enabled: true,
      surface: {
        tint: 'gold',
        tintStrength: 34,
        borderOpacityBoost: 24,
        lightStrengthBoost: 18,
        darkStrengthBoost: 8,
      },
      glow: {
        tone: 'gold',
        glowStrength: 56,
        corners: ['top-left', 'top-right', 'bottom-right', 'bottom-left'],
        edgeHighlight: ['top', 'bottom'],
        cornerSize: 18,
      },
      emission: {
        emission: 'rail-and-blip',
        emissionEdge: 'bottom',
        emissionTone: 'gold',
        emissionStrength: 70,
        emissionLength: 54,
        emissionThickness: 2,
        emissionBlipSize: 18,
      },
      content: {
        contentTone: 'black',
        iconTone: 'black',
        fontWeight: 800,
        fontStyle: 'normal',
        textTransform: 'uppercase',
        letterSpacing: 0.05,
      },
    },
    pressed: {
      enabled: true,
      surface: {
        tint: 'gold',
        tintStrength: 44,
        borderOpacityBoost: 28,
        lightStrengthBoost: 12,
        darkStrengthBoost: 16,
      },
      glow: {
        tone: 'gold',
        glowStrength: 68,
        corners: ['bottom-left', 'bottom-right'],
        edgeHighlight: ['bottom'],
        cornerSize: 18,
      },
      emission: {
        emission: 'center-blip',
        emissionEdge: 'bottom',
        emissionTone: 'gold',
        emissionStrength: 80,
        emissionLength: 36,
        emissionThickness: 3,
        emissionBlipSize: 20,
      },
      content: {
        contentTone: 'black',
        iconTone: 'inherit',
        fontWeight: 800,
        fontStyle: 'normal',
        textTransform: 'uppercase',
        letterSpacing: 0.05,
      },
      motion: {
        translateY: 1,
        scale: 0.985,
      },
    },
  }),
});

export const navBarContainerRecipe = createMaterialRecipe({
  material: 'custom',
  materialColor: '#121417',
  texture: 'none',
  shape: 'rect',
  glass: true,
  glassOpacity: 36,
  glassBlurEnabled: true,
  glassBlur: 12,
  tint: 'none',
  tintStrength: 0,
  gradient: 'none',
  borderEnabled: true,
  border: ['top'],
  borderColor: 'custom',
  borderCustomColor: '#eaeaea',
  borderOpacity: 22,
  dropShadow: true,
  shadowOpacity: 90,
  shadowBlur: 40,
  shadowX: 0,
  shadowY: -15,
  shadowSpread: 0,
  radius: 0,
});

