import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const CARDS_DIR = 'services/playgame/engine/manifest/card-sets/core-v1/cards';
export const GENERATED_PATH = 'services/playgame/engine/manifest/card-sets/core-v1/cards.generated.ts';

const toPascalCase = (id: string): string => (
  id
    .split('-')
    .map((part) => part.length === 0 ? '' : part[0].toUpperCase() + part.slice(1))
    .join('')
);

const readCardFolders = (): string[] => (
  readdirSync(CARDS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(CARDS_DIR, entry.name, 'card.json')))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b))
);

export const generateCardModulesSource = (): string => {
  const folders = readCardFolders();
  const imports = folders.map((folder) => {
    const binding = `${toPascalCase(folder)}Card`;
    return `import ${binding} from './cards/${folder}/card.json';`;
  });
  const entries = folders.map((folder) => {
    const binding = `${toPascalCase(folder)}Card`;
    return `  { folder: '${folder}', card: ${binding} as unknown as CardDef },`;
  });

  return [
    '// AUTO-GENERATED by npm run cards:generate. Do not edit by hand.',
    "import type { CardDef } from '../../types';",
    '',
    ...imports,
    '',
    'export const CORE_V1_CARD_MODULES: readonly { folder: string; card: CardDef }[] = [',
    ...entries,
    '];',
    '',
  ].join('\n');
};

const isMain = import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const args = new Set(process.argv.slice(2));
  const nextSource = generateCardModulesSource();

  if (args.has('--check')) {
    const current = existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, 'utf8') : '';
    if (current !== nextSource) {
      console.error(`${GENERATED_PATH} is stale. Run npm run cards:generate.`);
      process.exit(1);
    }
    console.log(`${GENERATED_PATH} is up to date.`);
  } else {
    writeFileSync(GENERATED_PATH, nextSource);
    console.log(`Generated ${GENERATED_PATH}.`);
  }
}
