import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const LOCATIONS_DIR = 'services/playgame/engine/manifest/location-sets/core-v1/locations';
export const GENERATED_LOCATION_PATH =
  'services/playgame/engine/manifest/location-sets/core-v1/locations.generated.ts';

const toPascalCase = (id: string): string => (
  id
    .split('-')
    .map((part) => part.length === 0 ? '' : part[0].toUpperCase() + part.slice(1))
    .join('')
);

const readLocationFolders = (): string[] => (
  readdirSync(LOCATIONS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(LOCATIONS_DIR, entry.name, 'location.json')))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b))
);

export const generateLocationModulesSource = (): string => {
  const folders = readLocationFolders();
  const imports = folders.map((folder) => {
    const binding = `${toPascalCase(folder)}Location`;
    return `import ${binding} from './locations/${folder}/location.json';`;
  });
  const entries = folders.map((folder) => {
    const binding = `${toPascalCase(folder)}Location`;
    return `  { folder: '${folder}', location: ${binding} as unknown as AuthoredLocationDef },`;
  });

  return [
    '// AUTO-GENERATED by npm run locations:generate. Do not edit by hand.',
    "import type { AuthoredLocationDef, LocationSetMetadata } from '../../location-set-loader';",
    "import CoreV1LocationSet from './set.json';",
    '',
    ...imports,
    '',
    'export const CORE_V1_LOCATION_SET = CoreV1LocationSet as unknown as LocationSetMetadata;',
    '',
    'export const CORE_V1_LOCATION_MODULES: readonly { folder: string; location: AuthoredLocationDef }[] = [',
    ...entries,
    '];',
    '',
  ].join('\n');
};

const isMain = import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const args = new Set(process.argv.slice(2));
  const nextSource = generateLocationModulesSource();

  if (args.has('--check')) {
    const current = existsSync(GENERATED_LOCATION_PATH)
      ? readFileSync(GENERATED_LOCATION_PATH, 'utf8')
      : '';
    if (current !== nextSource) {
      console.error(`${GENERATED_LOCATION_PATH} is stale. Run npm run locations:generate.`);
      process.exit(1);
    }
    console.log(`${GENERATED_LOCATION_PATH} is up to date.`);
  } else {
    writeFileSync(GENERATED_LOCATION_PATH, nextSource);
    console.log(`Generated ${GENERATED_LOCATION_PATH}.`);
  }
}
