
import { UserProfile, ProgressionData, ProgressionTrack } from '../../types';
import { REWARD_SEQUENCE } from './mockData';
import { progressionStore } from './mockDb';

/**
 * Calculates current progression for all tracks based on a Rolling Reward Waterfall.
 * Each track has a capacity and an offset.
 */
export const getProgressionDataInternal = (user: UserProfile): ProgressionData => {
    const GCL = user.level;

    const tracks: ProgressionTrack[] = REWARD_SEQUENCE.map((config, i) => {
        const totalPoints = GCL + config.offset;
        const currentProgress = totalPoints % config.capacity;
        const totalEarnedCount = Math.floor(totalPoints / config.capacity);
        
        // Unclaimed logic: Total rewards generated by level - rewards already taken
        const claimedCount = progressionStore.claimedCounts[i] || 0;
        const unclaimedCount = Math.max(0, totalEarnedCount - claimedCount);

        return {
            type: config.type,
            label: config.label,
            currentXP: currentProgress,
            targetXP: config.capacity,
            unclaimedCount,
            nextRewardAmount: config.amount,
        };
    });

    return { 
        collectionLevel: GCL, 
        tracks 
    };
};
